//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: iq/market/v1beta1/query.proto

package iq.market.v1beta1;

@kotlin.jvm.JvmSynthetic
inline fun queryParamsRequest(block: iq.market.v1beta1.QueryParamsRequestKt.Dsl.() -> Unit): iq.market.v1beta1.QueryOuterClass.QueryParamsRequest =
  iq.market.v1beta1.QueryParamsRequestKt.Dsl._create(iq.market.v1beta1.QueryOuterClass.QueryParamsRequest.newBuilder()).apply { block() }._build()
object QueryParamsRequestKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  class Dsl private constructor(
    @kotlin.jvm.JvmField private val _builder: iq.market.v1beta1.QueryOuterClass.QueryParamsRequest.Builder
  ) {
    companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: iq.market.v1beta1.QueryOuterClass.QueryParamsRequest.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): iq.market.v1beta1.QueryOuterClass.QueryParamsRequest = _builder.build()
  }
}
@kotlin.jvm.JvmSynthetic
inline fun iq.market.v1beta1.QueryOuterClass.QueryParamsRequest.copy(block: iq.market.v1beta1.QueryParamsRequestKt.Dsl.() -> Unit): iq.market.v1beta1.QueryOuterClass.QueryParamsRequest =
  iq.market.v1beta1.QueryParamsRequestKt.Dsl._create(this.toBuilder()).apply { block() }._build()
