//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: iq/market/v1beta1/query.proto

package iq.market.v1beta1;

@kotlin.jvm.JvmSynthetic
inline fun queryIqPoolDeltaResponse(block: iq.market.v1beta1.QueryIqPoolDeltaResponseKt.Dsl.() -> Unit): iq.market.v1beta1.QueryOuterClass.QueryIqPoolDeltaResponse =
  iq.market.v1beta1.QueryIqPoolDeltaResponseKt.Dsl._create(iq.market.v1beta1.QueryOuterClass.QueryIqPoolDeltaResponse.newBuilder()).apply { block() }._build()
object QueryIqPoolDeltaResponseKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  class Dsl private constructor(
    @kotlin.jvm.JvmField private val _builder: iq.market.v1beta1.QueryOuterClass.QueryIqPoolDeltaResponse.Builder
  ) {
    companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: iq.market.v1beta1.QueryOuterClass.QueryIqPoolDeltaResponse.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): iq.market.v1beta1.QueryOuterClass.QueryIqPoolDeltaResponse = _builder.build()

    /**
     * <pre>
     * iq_pool_delta defines the gap between the IqPool and the IqBasePool
     * </pre>
     *
     * <code>bytes iq_pool_delta = 1 [(.gogoproto.nullable) = false, (.gogoproto.customtype) = "github.com/cosmos/cosmos-sdk/types.Dec"];</code>
     */
    var iqPoolDelta: com.google.protobuf.ByteString
      @JvmName("getIqPoolDelta")
      get() = _builder.getIqPoolDelta()
      @JvmName("setIqPoolDelta")
      set(value) {
        _builder.setIqPoolDelta(value)
      }
    /**
     * <pre>
     * iq_pool_delta defines the gap between the IqPool and the IqBasePool
     * </pre>
     *
     * <code>bytes iq_pool_delta = 1 [(.gogoproto.nullable) = false, (.gogoproto.customtype) = "github.com/cosmos/cosmos-sdk/types.Dec"];</code>
     */
    fun clearIqPoolDelta() {
      _builder.clearIqPoolDelta()
    }
  }
}
@kotlin.jvm.JvmSynthetic
inline fun iq.market.v1beta1.QueryOuterClass.QueryIqPoolDeltaResponse.copy(block: iq.market.v1beta1.QueryIqPoolDeltaResponseKt.Dsl.() -> Unit): iq.market.v1beta1.QueryOuterClass.QueryIqPoolDeltaResponse =
  iq.market.v1beta1.QueryIqPoolDeltaResponseKt.Dsl._create(this.toBuilder()).apply { block() }._build()
