//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: iq/market/v1beta1/query.proto

package iq.market.v1beta1;

@kotlin.jvm.JvmSynthetic
inline fun queryIqPoolDeltaRequest(block: iq.market.v1beta1.QueryIqPoolDeltaRequestKt.Dsl.() -> Unit): iq.market.v1beta1.QueryOuterClass.QueryIqPoolDeltaRequest =
  iq.market.v1beta1.QueryIqPoolDeltaRequestKt.Dsl._create(iq.market.v1beta1.QueryOuterClass.QueryIqPoolDeltaRequest.newBuilder()).apply { block() }._build()
object QueryIqPoolDeltaRequestKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  class Dsl private constructor(
    @kotlin.jvm.JvmField private val _builder: iq.market.v1beta1.QueryOuterClass.QueryIqPoolDeltaRequest.Builder
  ) {
    companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: iq.market.v1beta1.QueryOuterClass.QueryIqPoolDeltaRequest.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): iq.market.v1beta1.QueryOuterClass.QueryIqPoolDeltaRequest = _builder.build()
  }
}
@kotlin.jvm.JvmSynthetic
inline fun iq.market.v1beta1.QueryOuterClass.QueryIqPoolDeltaRequest.copy(block: iq.market.v1beta1.QueryIqPoolDeltaRequestKt.Dsl.() -> Unit): iq.market.v1beta1.QueryOuterClass.QueryIqPoolDeltaRequest =
  iq.market.v1beta1.QueryIqPoolDeltaRequestKt.Dsl._create(this.toBuilder()).apply { block() }._build()
