//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: iq/oracle/v1beta1/tx.proto

package iq.oracle.v1beta1;

@kotlin.jvm.JvmSynthetic
inline fun msgAggregateExchangeRateVoteResponse(block: iq.oracle.v1beta1.MsgAggregateExchangeRateVoteResponseKt.Dsl.() -> Unit): iq.oracle.v1beta1.Tx.MsgAggregateExchangeRateVoteResponse =
  iq.oracle.v1beta1.MsgAggregateExchangeRateVoteResponseKt.Dsl._create(iq.oracle.v1beta1.Tx.MsgAggregateExchangeRateVoteResponse.newBuilder()).apply { block() }._build()
object MsgAggregateExchangeRateVoteResponseKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  class Dsl private constructor(
    @kotlin.jvm.JvmField private val _builder: iq.oracle.v1beta1.Tx.MsgAggregateExchangeRateVoteResponse.Builder
  ) {
    companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: iq.oracle.v1beta1.Tx.MsgAggregateExchangeRateVoteResponse.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): iq.oracle.v1beta1.Tx.MsgAggregateExchangeRateVoteResponse = _builder.build()
  }
}
@kotlin.jvm.JvmSynthetic
inline fun iq.oracle.v1beta1.Tx.MsgAggregateExchangeRateVoteResponse.copy(block: iq.oracle.v1beta1.MsgAggregateExchangeRateVoteResponseKt.Dsl.() -> Unit): iq.oracle.v1beta1.Tx.MsgAggregateExchangeRateVoteResponse =
  iq.oracle.v1beta1.MsgAggregateExchangeRateVoteResponseKt.Dsl._create(this.toBuilder()).apply { block() }._build()
