//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: iq/oracle/v1beta1/query.proto

package iq.oracle.v1beta1;

@kotlin.jvm.JvmSynthetic
inline fun queryTobinTaxRequest(block: iq.oracle.v1beta1.QueryTobinTaxRequestKt.Dsl.() -> Unit): iq.oracle.v1beta1.QueryOuterClass.QueryTobinTaxRequest =
  iq.oracle.v1beta1.QueryTobinTaxRequestKt.Dsl._create(iq.oracle.v1beta1.QueryOuterClass.QueryTobinTaxRequest.newBuilder()).apply { block() }._build()
object QueryTobinTaxRequestKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  class Dsl private constructor(
    @kotlin.jvm.JvmField private val _builder: iq.oracle.v1beta1.QueryOuterClass.QueryTobinTaxRequest.Builder
  ) {
    companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: iq.oracle.v1beta1.QueryOuterClass.QueryTobinTaxRequest.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): iq.oracle.v1beta1.QueryOuterClass.QueryTobinTaxRequest = _builder.build()

    /**
     * <pre>
     * denom defines the denomination to query for.
     * </pre>
     *
     * <code>string denom = 1;</code>
     */
    var denom: kotlin.String
      @JvmName("getDenom")
      get() = _builder.getDenom()
      @JvmName("setDenom")
      set(value) {
        _builder.setDenom(value)
      }
    /**
     * <pre>
     * denom defines the denomination to query for.
     * </pre>
     *
     * <code>string denom = 1;</code>
     */
    fun clearDenom() {
      _builder.clearDenom()
    }
  }
}
@kotlin.jvm.JvmSynthetic
inline fun iq.oracle.v1beta1.QueryOuterClass.QueryTobinTaxRequest.copy(block: iq.oracle.v1beta1.QueryTobinTaxRequestKt.Dsl.() -> Unit): iq.oracle.v1beta1.QueryOuterClass.QueryTobinTaxRequest =
  iq.oracle.v1beta1.QueryTobinTaxRequestKt.Dsl._create(this.toBuilder()).apply { block() }._build()
