//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: iq/treasury/v1beta1/query.proto

package iq.treasury.v1beta1;

@kotlin.jvm.JvmSynthetic
inline fun queryTaxRateRequest(block: iq.treasury.v1beta1.QueryTaxRateRequestKt.Dsl.() -> Unit): iq.treasury.v1beta1.QueryOuterClass.QueryTaxRateRequest =
  iq.treasury.v1beta1.QueryTaxRateRequestKt.Dsl._create(iq.treasury.v1beta1.QueryOuterClass.QueryTaxRateRequest.newBuilder()).apply { block() }._build()
object QueryTaxRateRequestKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  class Dsl private constructor(
    @kotlin.jvm.JvmField private val _builder: iq.treasury.v1beta1.QueryOuterClass.QueryTaxRateRequest.Builder
  ) {
    companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: iq.treasury.v1beta1.QueryOuterClass.QueryTaxRateRequest.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): iq.treasury.v1beta1.QueryOuterClass.QueryTaxRateRequest = _builder.build()
  }
}
@kotlin.jvm.JvmSynthetic
inline fun iq.treasury.v1beta1.QueryOuterClass.QueryTaxRateRequest.copy(block: iq.treasury.v1beta1.QueryTaxRateRequestKt.Dsl.() -> Unit): iq.treasury.v1beta1.QueryOuterClass.QueryTaxRateRequest =
  iq.treasury.v1beta1.QueryTaxRateRequestKt.Dsl._create(this.toBuilder()).apply { block() }._build()
