//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: iq/oracle/v1beta1/tx.proto

package iq.oracle.v1beta1;

@kotlin.jvm.JvmSynthetic
inline fun msgDelegateFeedConsentResponse(block: iq.oracle.v1beta1.MsgDelegateFeedConsentResponseKt.Dsl.() -> Unit): iq.oracle.v1beta1.Tx.MsgDelegateFeedConsentResponse =
  iq.oracle.v1beta1.MsgDelegateFeedConsentResponseKt.Dsl._create(iq.oracle.v1beta1.Tx.MsgDelegateFeedConsentResponse.newBuilder()).apply { block() }._build()
object MsgDelegateFeedConsentResponseKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  class Dsl private constructor(
    @kotlin.jvm.JvmField private val _builder: iq.oracle.v1beta1.Tx.MsgDelegateFeedConsentResponse.Builder
  ) {
    companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: iq.oracle.v1beta1.Tx.MsgDelegateFeedConsentResponse.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): iq.oracle.v1beta1.Tx.MsgDelegateFeedConsentResponse = _builder.build()
  }
}
@kotlin.jvm.JvmSynthetic
inline fun iq.oracle.v1beta1.Tx.MsgDelegateFeedConsentResponse.copy(block: iq.oracle.v1beta1.MsgDelegateFeedConsentResponseKt.Dsl.() -> Unit): iq.oracle.v1beta1.Tx.MsgDelegateFeedConsentResponse =
  iq.oracle.v1beta1.MsgDelegateFeedConsentResponseKt.Dsl._create(this.toBuilder()).apply { block() }._build()
