//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: iq/oracle/v1beta1/query.proto

package iq.oracle.v1beta1;

@kotlin.jvm.JvmSynthetic
inline fun queryAggregatePrevoteRequest(block: iq.oracle.v1beta1.QueryAggregatePrevoteRequestKt.Dsl.() -> Unit): iq.oracle.v1beta1.QueryOuterClass.QueryAggregatePrevoteRequest =
  iq.oracle.v1beta1.QueryAggregatePrevoteRequestKt.Dsl._create(iq.oracle.v1beta1.QueryOuterClass.QueryAggregatePrevoteRequest.newBuilder()).apply { block() }._build()
object QueryAggregatePrevoteRequestKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  class Dsl private constructor(
    @kotlin.jvm.JvmField private val _builder: iq.oracle.v1beta1.QueryOuterClass.QueryAggregatePrevoteRequest.Builder
  ) {
    companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: iq.oracle.v1beta1.QueryOuterClass.QueryAggregatePrevoteRequest.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): iq.oracle.v1beta1.QueryOuterClass.QueryAggregatePrevoteRequest = _builder.build()

    /**
     * <pre>
     * validator defines the validator address to query for.
     * </pre>
     *
     * <code>string validator_addr = 1;</code>
     */
    var validatorAddr: kotlin.String
      @JvmName("getValidatorAddr")
      get() = _builder.getValidatorAddr()
      @JvmName("setValidatorAddr")
      set(value) {
        _builder.setValidatorAddr(value)
      }
    /**
     * <pre>
     * validator defines the validator address to query for.
     * </pre>
     *
     * <code>string validator_addr = 1;</code>
     */
    fun clearValidatorAddr() {
      _builder.clearValidatorAddr()
    }
  }
}
@kotlin.jvm.JvmSynthetic
inline fun iq.oracle.v1beta1.QueryOuterClass.QueryAggregatePrevoteRequest.copy(block: iq.oracle.v1beta1.QueryAggregatePrevoteRequestKt.Dsl.() -> Unit): iq.oracle.v1beta1.QueryOuterClass.QueryAggregatePrevoteRequest =
  iq.oracle.v1beta1.QueryAggregatePrevoteRequestKt.Dsl._create(this.toBuilder()).apply { block() }._build()
